version: "3.8"

services:
  app:
    image: ghcr.io/openaegis/dujiaoka:${DOCKER_TAG:-latest}
    container_name: dujiaoka_app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      APP_NAME: ${APP_NAME:-独角数卡}
      APP_ENV: ${APP_ENV:-production}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-http://localhost:8080}
      APP_LOCALE: ${APP_LOCALE:-zh_CN}
      APP_FALLBACK_LOCALE: ${APP_FALLBACK_LOCALE:-zh_CN}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-dujiaoka}
      DB_USERNAME: ${DB_USERNAME:-dujiaoka}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_DRIVER: ${CACHE_DRIVER:-redis}
      SESSION_DRIVER: ${SESSION_DRIVER:-redis}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_CHANNEL: ${LOG_CHANNEL:-stack}
      DUJIAO_ADMIN_LANGUAGE: ${DUJIAO_ADMIN_LANGUAGE:-zh_CN}
      ADMIN_ROUTE_PREFIX: ${ADMIN_ROUTE_PREFIX:-/admin}
    volumes:
      - /opt/dujiaoka:/app
    depends_on:
      - mysql
      - redis
    networks:
      - dujiaoka

  mysql:
    image: mysql:8.0
    container_name: dujiaoka_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-dujiaoka}
      MYSQL_USER: ${DB_USERNAME:-dujiaoka}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /opt/dujiaoka/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dujiaoka

  redis:
    image: redis:7-alpine
    container_name: dujiaoka_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --save "" --stop-writes-on-bgsave-error no
    volumes:
      - /opt/dujiaoka/redis:/data
    user: "999:999"
    ports:
      - "6379:6379"
    networks:
      - dujiaoka

# 不再使用命名卷，直接挂载目录到 /opt/dujiaoka/mysql 和 /opt/dujiaoka/redis

networks:
  dujiaoka:
    driver: bridge
