name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get version info
      id: get_version
      run: |
        # Set default version
        DEFAULT_VERSION="2.1.0"
        
        # Get latest tag
        LATEST_TAG=$(git tag --sort=-version:refname | head -1 2>/dev/null || echo "")
        
        if [ -z "$LATEST_TAG" ]; then
          # No tags found, use default
          BASE_VERSION="$DEFAULT_VERSION"
          BUILD_NUMBER=$(git rev-list --count HEAD)
        else
          # Extract version number without 'v' prefix
          BASE_VERSION=${LATEST_TAG#v}
          # Generate build number based on commit count since last tag
          BUILD_NUMBER=$(git rev-list --count ${LATEST_TAG}..HEAD 2>/dev/null || echo "0")
        fi
        
        echo "base_version=$BASE_VERSION" >> $GITHUB_OUTPUT
        echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
        
        # Create version for main branch
        if [ "${{ github.ref_name }}" = "main" ]; then
          if [ "$BUILD_NUMBER" -gt "0" ]; then
            FULL_VERSION="${BASE_VERSION}-build.${BUILD_NUMBER}"
          else
            FULL_VERSION="$BASE_VERSION"
          fi
        else
          FULL_VERSION="$BASE_VERSION"
        fi
        
        echo "full_version=$FULL_VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $FULL_VERSION"

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          # For git tags: use semantic versioning
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          # For main branch: use computed version
          type=raw,value=${{ steps.get_version.outputs.full_version }},enable=${{ github.ref_name == 'main' && steps.get_version.outputs.full_version != '' }}
          # For main branch: always tag as latest  
          type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
          # For main branch: fallback version if full_version is empty
          type=raw,value=2.1.0-dev,enable=${{ github.ref_name == 'main' && steps.get_version.outputs.full_version == '' }}
          # For PR: use pr number
          type=ref,event=pr,prefix=pr-
          # For other branches: use branch name
          type=ref,event=branch,enable=${{ github.ref_name != 'main' }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1