name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get latest tag
      id: get_tag
      run: |
        # Get latest tag, fallback to v2.1.0 if no tags
        LATEST_TAG=$(git tag --sort=-version:refname | head -1 || echo "v2.1.0")
        echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
        
        # Generate build number based on commit count since last tag
        if [ -n "$(git tag)" ]; then
          BUILD_NUMBER=$(git rev-list --count ${LATEST_TAG}..HEAD)
        else
          BUILD_NUMBER=$(git rev-list --count HEAD)
        fi
        echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
        
        # Extract version number without 'v' prefix
        VERSION=${LATEST_TAG#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          # For tags: use exact version
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          # For main branch: use version + build number
          type=raw,value=${{ steps.get_tag.outputs.version }}-build.${{ steps.get_tag.outputs.build_number }},enable={{is_default_branch}}
          # For main branch: also tag as latest
          type=raw,value=latest,enable={{is_default_branch}}
          # For PR: use pr number
          type=ref,event=pr,prefix=pr-
          # For other branches: use branch name
          type=ref,event=branch,enable=${{ github.ref_name != 'main' }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1